# Site settings
title: Easy Theory
email: adam@furmanczuk.eu
description: The Jekyll version of the Spectral theme by HTML5 UP.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://easytheory.ch" # the base hostname & protocol for your site

plugins:
  - jekyll-sitemap

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 4

# Misc settings
featured-image-source:

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown
