# Site settings
email: adam@furmanczuk.eu
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://www.easytheory.ch" # the base hostname & protocol for your site
title: EasyTheory Theorieprüfung App Auto und Motorrad

plugins:
  - jekyll-sitemap

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 7

# Misc settings
featured-image-source:

# Social settings
500px_url:
facebook_url: https://www.facebook.com/Theoriepruefung.Auto/
github_url:
gitlab_url:
googleplus_url:
instagram_url: https://www.instagram.com/auto_theorie_lernen/
linkedin_url: https://www.linkedin.com/showcase/autotheorie-lernen/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/ALernen

# Build settings
markdown: kramdown
